package clash.back.exception;

public class ChallengeNotFoundException extends Exception {
}
